### ISSUE TITLE
Currículos.git

### ISSUE THREAD

**Issue by OliviaLZimmermann** [UNIVEM-BCC-BSI/Syschool#3]
Aqui contém o currículo de cada integrante do grupo.
[currículo olivia.pdf](https://github.com/UNIVEM-BCC-BSI/Syschool/files/11388645/curriculo.olivia.pdf)

**Comment by gisudario** [comment]
[Currículo_GiovannaSudario.pdf](https://github.com/UNIVEM-BCC-BSI/Syschool/files/11399934/Curriculo_GiovannaSudario.pdf)

**Comment by andrei-oliveira2004** [comment]
[Andrei- Currículo.pdf](https://github.com/UNIVEM-BCC-BSI/Syschool/files/11402423/Andrei-.Curriculo.pdf)

**Comment by juliartto** [comment]
[Currículo Julia.pdf](https://github.com/UNIVEM-BCC-BSI/Syschool/files/11409934/Curriculo.Julia.pdf)
